import type { Metadata } from "next";
import "./globals.css";
import { vazirmatn } from "@/public/fonts/vazirmatn/vazirmant";
import Providers from "./Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa">
      <body
        className={vazirmatn.className}
      >
        <Providers font={vazirmatn}>
          <main className="p-6 mx-auto container">
            {children}
          </main>
        </Providers>

      </body>
    </html>
  );
}
